version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.0.1
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command:
      - "--debug"
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/example-realm.json"
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./example-realm.json:/opt/jboss/keycloak/example-realm.json
